name: Build and Deploy Frontend WebApp

on:
  workflow_dispatch:
  pull_request:
    paths:
      - app/beacon-bridge-ui/**
      - .github/workflows/build.beacon-bridge-ui.yml

env:
  AZURE_WEBAPP_PACKAGE_PATH: app/beacon-bridge-ui
  NODE_VERSION: 24

jobs:
  build:
    name: Build Frontend Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build
        run: |
          npm i --workspaces=false
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 

      - name: Cache .next/cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH  }}/.next/cache
          key: nextjs | $(Agent.OS) | ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json

      - name: Build
        run: npm run build --workspaces=false
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
